<?php
/**
 * Created by IntelliJ IDEA.
 * User: Ruaa Elrasheed
 * Date: 07/12/2020
 * Time: 09:27
 */
namespace TigerTec\ShipIntegration\Model;

class SariOrderEstimationIds extends \Magento\Framework\Model\AbstractModel
{
    protected function _construct()
    {
        $this->_init(
            'TigerTec\ShipIntegration\Model\ResourceEstimationIdsModel\SariOrderEstimationIds'
        );
        //parent::_construct(); // TODO: Change the autogenerated stub
    }
}