<?php
/**
 * Created by IntelliJ IDEA.
 * User: Ruaa Elrasheed
 * Date: 10/09/2019
 * Time: 09:10
 */
namespace TigerTec\ShipIntegration\Model;

class Tracking extends \Magento\Framework\Model\AbstractModel
{
    const STATE_NEW_ORDER = 1;

    const STATE_MERCHANT_CONFITMED = 2;

    const STATE_IN_PROGRESS = 3;

    const STATE_DELIVERD = 4;

    const STATE_CANCELED = 5;

    const STATE_MERCHANT_NOT_REACHABLE = 6;

    const STATE_CUSTOMER_NOT_PRESENT = 7;

    const STATE_CUSTOMER_ISSUE = 8;

    const STATE_MERCHANT_ISSUE = 9;

    protected function _construct()
    {
        $this->_init('TigerTec\ShipIntegration\Model\ResourceModel\Tracking');
        //parent::_construct(); // TODO: Change the autogenerated stub
    }
}