<?php
/**
 * Created by IntelliJ IDEA.
 * User: Ruaa Elrasheed
 * Date: 10/09/2019
 * Time: 09:15
 */
namespace TigerTec\ShipIntegration\Model\ResourceModel\Tracking;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init(
            'TigerTec\ShipIntegration\Model\Tracking',
            'TigerTec\ShipIntegration\Model\ResourceModel\Tracking'
        );
        //parent::_construct(); // TODO: Change the autogenerated stub
    }
}